### ISSUE TITLE
HELP,HELP,Hash Rate Problem!

### ISSUE THREAD

**Issue by kimats** [xmrig/xmrig-proxy#126] opened 2018-03-08 07:46 UTC
Dear team,

I find some strange thing on hash rate, through the proxy, the hash rate is going down!  so I did some test to see what is going wrong, Please help my to get an answer:

If my miner starts to work, it will show you for example 100 hash rate, then on the pool site, you will have average per hour,  6 hours average, 24 hours average, normally, the 6 hours average and 24 hours average will be almost equals 100 hash rate.

My test likes below:

1. the miner has 60 hash rate, using proxy, the "6 hours average, 24 hours average" will be around 40 hash rate, **lose 20 hash rate**

2. then I add another miner to the proxy, which has  "6 hours average, 24 hours average“ is 260 hash rate, so technically speaking the total hash rates for "6 hours average, 24 hours average" will be 260+60=320 hash rate, but actually, the hash rate for "6 hours average, 24 hours average" is 210 hash rates, **lose 90 hash rate**

what is the problem here?

**Comment by kimats** [comment] 2018-03-08 07:46
@xmrig

**Comment by kimats** [comment] 2018-03-20 05:25
anyone can help me on this topic?

**Comment by xmrig** [comment] 2018-03-22 01:13
Close as duplicate of original cause #123

**Closed by xmrig** 2018-03-22 01:13 UTC
