### ISSUE TITLE
Lost 20% Hash Rate when Using xmrig-proxy - Please Have a look!!

### ISSUE THREAD

**Issue by kimats** [xmrig/xmrig-proxy#141] opened 2018-03-20 15:33 UTC
Hello, @xmrig

I opened several ticket regarding on the "hash rate" issue:
https://github.com/xmrig/xmrig-proxy/issues/126
https://github.com/xmrig/xmrig-proxy/issues/138

**Since no one reply me, I did a test to approve the issue definitely exist!, please have a look:**

I have 23 old miners, and their hash rate is around 5.5KH/S in all!

When I use xmrig-proxy, by running it for 3 days, the hash rate at pool site is 4.36KH/S 

When I use other proxy, by running it for 3 days, the hash rate at pool site is around 5.4KH/S

**So, using xmrig-proxy is around 20% hash rate lost.... What happened here?**

I have turned on the nicehash switch..

Please have a look, beacuse I love to use xmrig

**Comment by xmrig** [comment] 2018-03-21 00:42
Please provide all positive details:

* Address and port of your pool, if don't want make it public you can send email.
* What diff used, fixed or automatic, if automatic enable verbose mode on proxy side (press `v` or via config) and view real diff and how often proxy found shares.
* What latency (ping) between proxy and pool and between miners and proxy.
* Did you update miners and proxy to v2.5? It required because of another your issue #123
* Provide hashrate report (`h` key) and at least one `accepted` line from proxy log.

Thank you.

**Comment by kimats** [comment] 2018-03-21 01:53
@xmrig 
Thanks man!!

Please provide all positive details:

Address and port of your pool, if don't want make it public you can send email.
**an e-mail has been sent to support@xmrig.com for the address and port.**

What diff used, fixed or automatic, if automatic enable verbose mode on proxy side (press v or via config) and view real diff and how often proxy found shares.
**I am not a guru, so just use default configuration, here is the output by press v:**
 * COMMANDS:     hashrate, connections, verbose, workers
[2018-03-21 09:32:50] verbose: 1
[2018-03-21 09:32:51] #000 accepted (1/0+0) diff 10000 (102 ms)
[2018-03-21 09:32:52] #000 accepted (2/0+0) diff 10000 (120 ms)
[2018-03-21 09:32:54] #000 accepted (3/0+0) diff 10000 (121 ms)
[2018-03-21 09:32:55] #000 accepted (4/0+0) diff 10000 (115 ms)
[2018-03-21 09:32:58] #000 accepted (5/0+0) diff 10000 (124 ms)
[2018-03-21 09:33:06] #000 accepted (6/0+0) diff 10000 (112 ms)
[2018-03-21 09:33:06] #000 accepted (7/0+0) diff 10000 (119 ms)
[2018-03-21 09:33:07] #000 accepted (8/0+0) diff 10000 (118 ms)
[2018-03-21 09:33:07] #000 accepted (9/0+0) diff 10000 (118 ms)
[2018-03-21 09:33:14] #000 accepted (10/0+1) diff 24073 (120 ms)
[2018-03-21 09:33:15] #000 accepted (11/0+1) diff 24073 (120 ms)
[2018-03-21 09:33:20] #000 accepted (12/0+1) diff 24073 (103 ms)
[2018-03-21 09:33:27] #000 accepted (13/0+1) diff 24073 (118 ms)
[2018-03-21 09:33:32] #000 accepted (14/0+1) diff 24073 (101 ms)
[2018-03-21 09:33:33] #000 accepted (15/0+1) diff 24073 (98 ms)
[2018-03-21 09:33:37] #000 accepted (16/0+1) diff 24073 (118 ms)
[2018-03-21 09:33:40] #000 accepted (17/0+1) diff 24073 (103 ms)
[2018-03-21 09:33:42] #000 accepted (18/0+1) diff 24073 (122 ms)
[2018-03-21 09:33:51] #000 accepted (19/0+1) diff 24073 (104 ms)
[2018-03-21 09:34:05] #000 accepted (20/0+1) diff 24073 (121 ms)
[2018-03-21 09:34:10] #000 accepted (21/0+1) diff 23343 (114 ms)
[2018-03-21 09:34:16] #000 accepted (22/0+1) diff 23343 (119 ms)
[2018-03-21 09:34:20] #000 accepted (23/0+1) diff 23343 (119 ms)
[2018-03-21 09:34:22] #000 accepted (24/0+1) diff 23343 (109 ms)
[2018-03-21 09:34:35] #000 accepted (25/0+1) diff 23343 (112 ms)
 
What latency (ping) between proxy and pool and between miners and proxy.
**the ping output looks like below:**
64 bytes from : icmp_seq=5 ttl=41 time=194 ms
64 bytes from : icmp_seq=6 ttl=41 time=195 ms
64 bytes from : icmp_seq=7 ttl=41 time=194 ms
64 bytes from : icmp_seq=8 ttl=41 time=195 ms
64 bytes from : icmp_seq=9 ttl=41 time=194 ms

Did you update miners and proxy to v2.5? It required because of another your issue #123
**Yes, all the miners have been upgraded to v2.5**

Provide hashrate report (h key) and at least one accepted line from proxy log.
**Here is the information of press h key:**

[2018-03-21 09:35:05] * speed (1m) 5.07, (10m) 1.06, (1h) 0.18, (12h) 0.01, (24h) 0.01 kH/s
[2018-03-21 09:35:09] * speed (1m) 5.07, (10m) 1.06, (1h) 0.18, (12h) 0.01, (24h) 0.01 kH/s

**since I switch back to xmrig-proxy for trouble shooting, wait several minutes to press h again:**

[2018-03-21 09:42:16] * speed (1m) 4.61, (10m) 4.31, (1h) 0.72, (12h) 0.06, (24h) 0.03 kH/s

[2018-03-21 09:53:15] * speed (1m) 3.78, (10m) 4.40, (1h) 1.52, (12h) 0.13, (24h) 0.06 kH/s

Thank you.

**Comment by xmrig** [comment] 2018-03-21 02:18
Proxy need be update to v2.5 too, if you use Windows and hard for you I can build it for you.
Thank you.

**Comment by kimats** [comment] 2018-03-21 02:27
Hello,

I use Ubuntu, so easy to build. however, https://github.com/xmrig/xmrig-proxy/releases , it is still 2.4.5?

I already build proxy  when you release 2.5 for xmrig by : 
git clone https://github.com/xmrig/xmrig-proxy.git
cd xmrig-proxy
mkdir build
cd build
cmake ..
make

but proxy still say it is 2.4.5

**Comment by kimats** [comment] 2018-03-21 03:31
@xmrig 

Hello, by using the xmrig-proxy 2.5.0, the problem has been solved! Please close this issue!!

The hash rate is higher than other proxy software! 

Excellent PROXY !!!

**Comment by xmrig** [comment] 2018-03-22 01:12
Close as duplicate of original cause #123

**Closed by xmrig** 2018-03-22 01:12 UTC

**Comment by darrynza** [comment] 2018-03-24 00:56
Where is version 2.5 ?? the code page is only talking about 2.4.5??

**Comment by xmrig** [comment] 2018-03-24 02:01
In [dev](https://github.com/xmrig/xmrig-proxy/tree/dev) branch, [changes overview](https://github.com/xmrig/xmrig-proxy/issues/119) and [change log](https://github.com/xmrig/xmrig-proxy/blob/dev/CHANGELOG.md). v2.5 almost finished and will be released in few days.
Thank you.
