### ISSUE TITLE
nicehash

### ISSUE THREAD

**Issue by mikef147** [xmrig/xmrig-proxy#14] opened 2017-08-30 14:01 UTC
The proxy doesn't work with nicehash? I have the --nicehash option going on miners to this proxy, but all shares still rejected from nicehash server.

**Comment by xmrig** [comment] 2017-08-30 19:06
Yep you can't use this proxy with nicehash.com, but miners required be nicehash comparable. Proxy works like nicehash, use same method to reduce connection count.
Thank you.

**Comment by MultiMiner** [comment] 2017-09-05 19:07
And nothing can be done? Nisehash is very convenient, like this proxy.

**Comment by xmrig** [comment] 2017-09-06 14:01
Sorry it can't fixed by design, only one nicehash proxy possible in chain, nicehash.com itself or this proxy.

**Comment by MultiMiner** [comment] 2017-09-06 21:16
Very sad ( The proxy about which Nicehash writes, the stratum-proxy, does not support cryptonight ((

**Comment by rinaldohack** [comment] 2017-09-15 14:37
So, let me get this straight. You are emulating how nicehash.com work, don't you?

**Comment by xmrig** [comment] 2017-09-15 15:00
Exactly right.

**Comment by rinaldohack** [comment] 2017-10-10 02:12
any way we could turn this into nicehash.com proxy? I have many workers, but with wrong username :(

**Comment by madscientist159** [comment] 2017-12-24 21:15
What is the exact technical reason this proxy can't connect to nicehash?

**Closed** 2017-12-30 04:19 UTC

**Comment by jnicholls** [comment] 2018-01-03 19:18
I'd like to know the technical reason as well.  Couldn't it simply pass off to nicehash the same as the `xmrig` miner would, but after the combining of the nonce work from client miners?

**Comment by ddebin** [comment] 2018-01-24 09:54
#83
